[package]
name = "heartbeat"
version = "0.1.0"
description = "A service to keep a live heartbeat on multiple devices"
edition = "2021"
license = "MPL-2.0"
authors = ["VJ <root@5ht2.me>"]
repository = "https://github.com/lmaotrigine/heartbeat"
homepage = "https://hb.5ht2.me"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.23", features = ["serde", "std", "clock"], default-features = false }
lazy_static = "1.4.0"
tokio = { version = "1.24.2", features = ["full"] }
serde = { version = "1.0.152", features = ["derive"] }
sqlx = { version = "0.7", features = ["postgres", "runtime-tokio-rustls", "macros", "chrono"] }
toml = "0.7.6"
base64 = "0.21.0"
rand = "0.8.5"

regex  = { version = "1.7.1", optional = true }
reqwest = { version = "0.11.13", features = ["json"], optional = true }
axum = { version = "0.6.19", features = ["macros", "ws", "tokio"] }
html = { git = "https://git.5ht2.me/lmaotrigine/html-rs", version = "0.1.0", features = ["axum"] }
serde_json = "1.0.104"
tower-http = { version = "0.4.3", features = ["fs"] }
tracing-subscriber = "0.3.17"
tracing = "0.1.37"
axum-realip = { git = "https://git.5ht2.me/lmaotrigine/axum-realip", version = "0.1.0" }

[features]
default = []
badges = ["regex"]
webhook = ["reqwest"]
