on:
  push:
  pull_request:
    types:
      - "opened"
      - "reopened"
      - "synchronize"

jobs:
  check:
    runs-on: ubuntu-latest
    name: "Check rust stable"
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: setup latest rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy, rustfmt
          override: true
      - name: setup nextest
        uses: lmaotrigine/fetch-crate-action@mistress
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          owner: nextest-rs
          name: nextest
      - name: setup just
        uses: lmaotrigine/fetch-crate-action@mistress
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          owner: casey
          name: just
      - name: check
        run: |
          just check
