on:
  push:
  pull_request:
    types:
      - "opened"
      - "reopened"
      - "synchronize"

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        include:
          - build: pinned
            rust: 1.74.0
          - build: stable
            rust: stable
          - build: beta
            rust: beta
          - build: nightly
            rust: nightly
    runs-on: ubuntu-latest
    name: "Check rust ${{ matrix.rust }}"
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ matrix.build }}-${{ hashFiles('**/Cargo.lock') }}
      - name: setup rust ${{ matrix.rust }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          components: clippy, rustfmt
      - name: setup nextest
        uses: lmaotrigine/fetch-crate-action@mistress
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          owner: nextest-rs
          name: nextest
          bin: cargo-nextest
      - name: setup just
        uses: lmaotrigine/fetch-crate-action@mistress
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          owner: casey
          name: just
      - name: setup ripgrep
        uses: lmaotrigine/fetch-crate-action@mistress
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          owner: BurntSushi
          name: ripgrep
          bin: rg
      - name: setup mdbook
        uses: lmaotrigine/fetch-crate-action@mistress
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          owner: rust-lang
          name: mdBook
          bin: mdbook
      - name: setup mdbook-linkcheck
        uses: lmaotrigine/fetch-crate-action@mistress
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          owner: Michael-F-Bryan
          name: mdbook-linkcheck
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: install dependencies
        run: |
          npm install -g stylelint typescript eslint
          npm install
      - name: check and test
        run: |
          just ci
        shell: bash
        env:
          RUST_TOOLCHAIN: ${{ matrix.rust }}
